config/routes.rb
Rails.application.routes.draw do
  
  resources :tweets, only: [:index, :new, :create, :edit, :update, :destroy] do
    collection do 
      post :confirm
    end
  end
  
  root 'tweets#index'
  

end

app/models/tweet.rb
class Tweet < ActiveRecord::Base
    validates :content, presence: true
    validates :content, length: {maximum: 255}
    
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
    
    before_action :set_tweet, only: [:edit, :update, :destroy]
    
    def index
        @tweets = Tweet.all
        
        if params[:back]
            @tweet = Tweet.new(tweets_params)
        else
            @tweet = Tweet.new
        end
    end
   
    def new
        if params[:back]
            @tweet = Tweet.new(tweets_params)
        else
            @tweet = Tweet.new
        end
    end
    
    def create
        @tweet = Tweet.new(tweets_params)
        if @tweet.save
            redirect_to tweets_path, notice: "ツイートしました！"
        else
            render action: 'new'
        end
    end
    
    def edit
    end
        
    def update
        if @tweet.update(tweets_params)
            redirect_to tweets_path, notice: "編集しました！"
        else
            render action: 'edit'
        end
    end
    
    def destroy
        @tweet.destroy
        redirect_to tweets_path
    end
    
    def confirm
        @tweet = Tweet.new(tweets_params)
        render 'new' if @tweet.invalid?
    end
    
    
    private
        def tweets_params
            params.require(:tweet).permit(:content)
            
        end
        
        def set_tweet
            @tweet = Tweet.find(params[:id])
        end
    
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
    def choose_new_or_edit
    if action_name == 'new' || action_name == 'confirm' || action_name == 'index'
      confirm_tweets_path
    elsif action_name == 'edit'
      tweet_path
    end
    end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Dive07Exam</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1">
</head>
<body>

<%= yield %>

</body>
</html>

app/views/tweets/_form.html.erb
<%= form_for(@tweet, url: choose_new_or_edit) do |f| %>
 <% if @tweet.errors.any? %>
 
   <h2><%= @tweet.errors.count %>件のエラーがあります。</h2>
   
   <ul>
     <% @tweet.errors.full_messages.each do |msg| %>
       <li><%= msg %></li>
     <% end %>
     
   </ul>
 
 <% end %>
  
  
  <%= f.label :content %>
  <%= f.text_field :content, class: 'form-control' %>
  <br>
  <%= f.submit '投稿', class: 'btn btn-primary btn-block' %>
  <br>
<% end %>

app/views/tweets/confirm.html.erb
<div class="container">

<h1>確認画面</h1>

<%= form_for(@tweet) do |f| %>

    <%= f.hidden_field :content %>
    
    <p>本文：<%= @tweet.content %></p>
    <p><%= f.submit "投稿",class: 'btn btn-primary btn-block' %></p>
<% end %>

<%= form_for(@tweet, url: tweets_path, method: 'get') do |f| %>
  <%= f.hidden_field :content %>
  <p><%= f.submit "もどる", name: 'back',class: 'btn btn-primary btn-block' %></p>
<% end %>

</div>

app/views/tweets/edit.html.erb
<div class="container">


<h1>ツイートを編集</h1>

<%= render 'form' %>
<br>
<%= link_to "ツイート一覧を見る", tweets_path %>

</div>

app/views/tweets/index.html.erb
<div class="container">
    <div class="col-md-12 col-md-offset-0 col-sm-10 col-sm-offset-0">
        <div class="row">
    
    
<%= render 'form' %>


<h1>ツイート一覧</h1>
        </div>
    
    <% @tweets.each do |tweet| %>
    <div class="row" id="content"> 
    <p>コンテンツ：<%= tweet.content %></p>
    
    <p>
    <%= link_to "ツイートを編集する", edit_tweet_path(tweet.id), class: 'btn btn-default btn-sm btn-success' %></li>
    <%= link_to "ツイートを削除する", tweet_path(tweet), method: :delete, data: { confirm: '本当に削除していいですか？' }, class: 'btn btn-default btn-sm btn btn-danger' %>
    </p>
    </div>
    <% end %>
    </div>
    
    <div class="clear"></div>
    
    <div id="page-top-btn" class="page-top-btn">
    <p><a class="move-page-top" id="move-page-top">▲</a></p>
    </div>
    
</div>

app/views/tweets/new.html.erb
<div class="container">

<%= render 'form' %>

</div>